export const actionTypes = {
    //app
    PROCESS_APP_ACTION: "PROCESS_APP_ACTION",
    PROCESS_APP_ACTION_FAILED: "PROCESS_APP_ACTION_FAILED",
    PROCESS_ACTION: "PROCESS_ACTION",
    PROCESS_ACTION_FAILED: "PROCESS_ACTION_FAILED",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOG_OUT: "LOG_OUT",

    //user
    FETCH_DATA_HOME_SUCCESS: "FETCH_DATA_HOME_SUCCESS",
    FETCH_DATA_FLASHSALE_SUCCESS: "FETCH_DATA_FLASHSALE_SUCCESS",
    FETCH_DATA_SUPER_FLASHSALE_SUCCESS: "FETCH_DATA_SUPER_FLASHSALE_SUCCESS",
    FETCH_DATA_MEGASALE_SUCCESS: "FETCH_DATA_MEGASALE_SUCCESS",
    FETCH_DATA_WISHLIST_SUCCESS: "FETCH_DATA_WISHLIST_SUCCESS",
    FETCH_DATA_CART_SUCCESS: "FETCH_DATA_CART_SUCCESS",
    FETCH_DATA_RECOMMEND_SUCCESS: "FETCH_DATA_RECOMMEND_SUCCESS",
    FETCH_HOME_CATEGORY_SUCCESS: "FETCH_HOME_CATEGORY_SUCCESS",
    FETCH_ALL_CATEGORY_SUCCESS: "FETCH_ALL_CATEGORY_SUCCESS",
    FETCH_USER_ADDRESS_SUCCESS: "FETCH_USER_ADDRESS_SUCCESS",
    FETCH_NEW_TOKEN_SUCCESS: "FETCH_NEW_TOKEN_SUCCESS",
    FETCH_NEW_TOKEN_FAILED: "FETCH_NEW_TOKEN_FAILED",
    APPLY_CUPON_CODE: "APPLY_CUPON_CODE",
    FETCH_DATA_PAYMENT: "FETCH_DATA_PAYMENT",
    HANDLE_CHANGE_WISHLIST_SUCCESS: "HANDLE_CHANGE_WISHLIST_SUCCESS",
    REMOVE_FROM_WISHLIST_SUCCESS: "REMOVE_FROM_WISHLIST_SUCCESS",
    CHANGE_CART: "CHANGE_CART",
    CHANGE_QUANTITY: "CHANGE_QUANTITY",
    CALCULATE_BILL: "CALCULATE_BILL",
    RESET_BILL: "RESET_BILL",
    CHANGE_USER_INFO: "CHANGE_USER_INFO"
}